---
title: "Project_2_Scripts"
author: "Mo Hijazi"
date: "11/17/2021"
output: html_document
---
Function(s):
```{r}
# This function creates a malaria map for a specific year.
Malaria.Map.F <- function(df.year,year,save.name){ 
  #df.year = the data frame to be used for the map.
  #year = the year the map will represent
  #save.name = the file name the map should be saved as. 
#Saving the world map data to the data frame "mapdata."
  mapdata <- map_data("world")
  intermediate_malaria <- df.year %>% #Assigning the "malaria.all.x" data frame to "d" which is a intermediate data frame. 
  right_join(mapdata, by= "region") %>%
  group_by(region) %>% #Groups the malria data witht he world map using regions. 
  filter_if(~is.numeric(.), all_vars(!is.infinite(.)))

intermediate_malaria <- subset(intermediate_malaria, select = -7) #Removing unneeded columns.
intermediate_malaria$deaths <- log(intermediate_malaria$deaths) #Loging all deaths to create a better visual representation. 
#Creating the map using virdis colors.
wtihout_canvas = ggplot(intermediate_malaria , aes(long, lat, group = group)) +
  geom_polygon(aes(fill = deaths), na.rm ="black") + 
  scale_fill_viridis(name = "Number of Deaths", breaks = c(2,10), labels = c("Low death rates", "High death rates"), limits = c(0,12)) +
  labs(title = paste("Average Number of Malaria Related Deaths in Different Countries (Year:",year,")"),
       caption = "** Gray regions do not have malaria deaths or data pretaining to number of malaria deaths **") +
  theme_void()
#Saving the map to a folder called "results."
ggsave(path = "results", save.name,height = 6, width=9) 
}
```

Visual 1 - Data clean up: 
```{r, include=T}
#Renaming specific countries on the data to match the world map names.
malaria$Entity[1401:1428] <- "Ivory Coast"
malaria$Entity[1345:1372] <- "Democratic Republic of the Congo"
malaria$Entity[1541:1568] <- "Democratic Republic of the Congo"
malaria$Entity[1065:1092] <- "China"
malaria$Entity[1121:1148] <- "Spain"
malaria$Entity[1681:1708] <- "China"
malaria$Entity[5209:5236] <- "China"
malaria$Entity[5293:5348] <- "China"

#Making sure the data is numeric for calculations.
malaria$Entity <- factor(malaria$Entity) 
#Cleaning up the column names, removing unneeded columns, and omitting any NA values.
malaria <- malaria %>% clean_names() %>%
  subset( select = -2) %>% 
  na.omit()
```

Visual 2 - Data clean up: 
```{r}
#creating a data frame with just "world" death counts
Visual2malaria <- data.frame(Visual2malaria[6357:6384, ]) 
#Removing unneeded columns
Visual2malaria <- subset(Visual2malaria, select = -2)
Visual2malaria <- subset(Visual2malaria, select = -1)
#making year counts as characters for easier visual edits. 
Visual2malaria$Year <- as.character(Visual2malaria$Year)
#Combining column deaths. 
total.deaths <- rowSums(Visual2malaria[, 2:6])
year <- Visual2malaria$Year
```